export const CLI_UPDATE_TEST_MODE_ENV = "JUMBO_CLI_UPDATE_TEST_MODE";
export const CLI_UPDATE_TEST_VERSION_ENV = "JUMBO_CLI_UPDATE_TEST_VERSION";
export const CLI_UPDATE_TEST_UPGRADE_DELAY_MS_ENV =
  "JUMBO_CLI_UPDATE_TEST_UPGRADE_DELAY_MS";
export const CLI_UPDATE_TEST_UPGRADE_RESULT_ENV =
  "JUMBO_CLI_UPDATE_TEST_UPGRADE_RESULT";
