export const SubprocessCopy = {
  terminationRequested: "termination requested",
  processStopped: "process stopped",
  processFailed: "process failed",
  spawnRequestedLog: "Daemon subprocess spawn requested",
  startedLog: "Daemon subprocess started",
  stdoutLog: "Daemon subprocess stdout",
  stderrLog: "Daemon subprocess stderr",
  closedLog: "Daemon subprocess closed",
  errorLog: "Daemon subprocess error",
  terminationRequestedLog: "Daemon subprocess termination requested",
  terminationCompletedLog: "Daemon subprocess termination completed",
  terminationFailedLog: "Daemon subprocess termination failed",
  terminationTimedOutLog: "Daemon subprocess termination timed out",
  eventLog: "Daemon subprocess event",
} as const;
