/**
 * Auto-generated Command Registry
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated by: scripts/generate-command-registry.mjs
 *
 * To regenerate: npm run generate:commands
 */

import { RegisteredCommand } from './CommandMetadata.js';

import { architectureDefine, metadata as architectureDefineMeta } from '../../commands/architecture/define/architecture.define.js';
import { architectureUpdate, metadata as architectureUpdateMeta } from '../../commands/architecture/update/architecture.update.js';
import { architectureView, metadata as architectureViewMeta } from '../../commands/architecture/view/architecture.view.js';
import { audiencePainAdd, metadata as audiencePainAddMeta } from '../../commands/audience-pains/add/audiencePain.add.js';
import { audiencePainsList, metadata as audiencePainsListMeta } from '../../commands/audience-pains/list/audiencePains.list.js';
import { audiencePainUpdate, metadata as audiencePainUpdateMeta } from '../../commands/audience-pains/update/audiencePain.update.js';
import { audienceAdd, metadata as audienceAddMeta } from '../../commands/audiences/add/audience.add.js';
import { audiencesList, metadata as audiencesListMeta } from '../../commands/audiences/list/audiences.list.js';
import { audienceRemove, metadata as audienceRemoveMeta } from '../../commands/audiences/remove/audience.remove.js';
import { audienceUpdate, metadata as audienceUpdateMeta } from '../../commands/audiences/update/audience.update.js';
import { componentAdd, metadata as componentAddMeta } from '../../commands/components/add/component.add.js';
import { componentDeprecate, metadata as componentDeprecateMeta } from '../../commands/components/deprecate/component.deprecate.js';
import { componentsList, metadata as componentsListMeta } from '../../commands/components/list/components.list.js';
import { componentRemove, metadata as componentRemoveMeta } from '../../commands/components/remove/component.remove.js';
import { componentRename, metadata as componentRenameMeta } from '../../commands/components/rename/component.rename.js';
import { componentsSearch, metadata as componentsSearchMeta } from '../../commands/components/search/components.search.js';
import { componentShow, metadata as componentShowMeta } from '../../commands/components/show/component.show.js';
import { componentUndeprecate, metadata as componentUndeprecateMeta } from '../../commands/components/undeprecate/component.undeprecate.js';
import { componentUpdate, metadata as componentUpdateMeta } from '../../commands/components/update/component.update.js';
import { decisionAdd, metadata as decisionAddMeta } from '../../commands/decisions/add/decision.add.js';
import { decisionsList, metadata as decisionsListMeta } from '../../commands/decisions/list/decisions.list.js';
import { decisionRestore, metadata as decisionRestoreMeta } from '../../commands/decisions/restore/decision.restore.js';
import { decisionReverse, metadata as decisionReverseMeta } from '../../commands/decisions/reverse/decision.reverse.js';
import { decisionSupersede, metadata as decisionSupersedeMeta } from '../../commands/decisions/supersede/decision.supersede.js';
import { decisionUpdate, metadata as decisionUpdateMeta } from '../../commands/decisions/update/decision.update.js';
import { dependencyAdd, metadata as dependencyAddMeta } from '../../commands/dependencies/add/dependency.add.js';
import { dependenciesList, metadata as dependenciesListMeta } from '../../commands/dependencies/list/dependencies.list.js';
import { dependencyRemove, metadata as dependencyRemoveMeta } from '../../commands/dependencies/remove/dependency.remove.js';
import { dependencyUpdate, metadata as dependencyUpdateMeta } from '../../commands/dependencies/update/dependency.update.js';
import { evolve, metadata as evolveMeta } from '../../commands/evolve/evolve.js';
import { goalAdd, metadata as goalAddMeta } from '../../commands/goals/add/goal.add.js';
import { goalApprove, metadata as goalApproveMeta } from '../../commands/goals/approve/goal.approve.js';
import { goalBlock, metadata as goalBlockMeta } from '../../commands/goals/block/goal.block.js';
import { goalClose, metadata as goalCloseMeta } from '../../commands/goals/close/goal.close.js';
import { goalCodify, metadata as goalCodifyMeta } from '../../commands/goals/codify/goal.codify.js';
import { goalCommit, metadata as goalCommitMeta } from '../../commands/goals/commit/goal.commit.js';
import { goalsList, metadata as goalsListMeta } from '../../commands/goals/list/goals.list.js';
import { goalPause, metadata as goalPauseMeta } from '../../commands/goals/pause/goal.pause.js';
import { goalQualify, metadata as goalQualifyMeta } from '../../commands/goals/qualify/goal.qualify.js';
import { goalRefine, metadata as goalRefineMeta } from '../../commands/goals/refine/goal.refine.js';
import { goalReject, metadata as goalRejectMeta } from '../../commands/goals/reject/goal.reject.js';
import { goalRemove, metadata as goalRemoveMeta } from '../../commands/goals/remove/goal.remove.js';
import { goalReset, metadata as goalResetMeta } from '../../commands/goals/reset/goal.reset.js';
import { goalResume, metadata as goalResumeMeta } from '../../commands/goals/resume/goal.resume.js';
import { goalReview, metadata as goalReviewMeta } from '../../commands/goals/review/goal.review.js';
import { goalShow, metadata as goalShowMeta } from '../../commands/goals/show/goal.show.js';
import { goalStart, metadata as goalStartMeta } from '../../commands/goals/start/goal.start.js';
import { goalSubmit, metadata as goalSubmitMeta } from '../../commands/goals/submit/goal.submit.js';
import { goalUnblock, metadata as goalUnblockMeta } from '../../commands/goals/unblock/goal.unblock.js';
import { goalUpdate, metadata as goalUpdateMeta } from '../../commands/goals/update/goal.update.js';
import { goalUpdateProgress, metadata as goalUpdateProgressMeta } from '../../commands/goals/update-progress/goal.update-progress.js';
import { guidelineAdd, metadata as guidelineAddMeta } from '../../commands/guidelines/add/guideline.add.js';
import { guidelinesList, metadata as guidelinesListMeta } from '../../commands/guidelines/list/guidelines.list.js';
import { guidelineRemove, metadata as guidelineRemoveMeta } from '../../commands/guidelines/remove/guideline.remove.js';
import { guidelineUpdate, metadata as guidelineUpdateMeta } from '../../commands/guidelines/update/guideline.update.js';
import { heal, metadata as healMeta } from '../../commands/heal/heal.js';
import { workerView, metadata as workerViewMeta } from '../../commands/host/workers/worker.view.js';
import { invariantAdd, metadata as invariantAddMeta } from '../../commands/invariants/add/invariant.add.js';
import { invariantsList, metadata as invariantsListMeta } from '../../commands/invariants/list/invariants.list.js';
import { invariantRemove, metadata as invariantRemoveMeta } from '../../commands/invariants/remove/invariant.remove.js';
import { invariantUpdate, metadata as invariantUpdateMeta } from '../../commands/invariants/update/invariant.update.js';
import { projectInit, metadata as projectInitMeta } from '../../commands/project/init/project.init.js';
import { projectUpdate, metadata as projectUpdateMeta } from '../../commands/project/update/project.update.js';
import { relationAdd, metadata as relationAddMeta } from '../../commands/relations/add/relation.add.js';
import { relationsList, metadata as relationsListMeta } from '../../commands/relations/list/relations.list.js';
import { relationRemove, metadata as relationRemoveMeta } from '../../commands/relations/remove/relation.remove.js';
import { sessionCompact, metadata as sessionCompactMeta } from '../../commands/sessions/compact/session.compact.js';
import { sessionEnd, metadata as sessionEndMeta } from '../../commands/sessions/end/session.end.js';
import { sessionsList, metadata as sessionsListMeta } from '../../commands/sessions/list/sessions.list.js';
import { sessionStart, metadata as sessionStartMeta } from '../../commands/sessions/start/session.start.js';
import { telemetryDisable, metadata as telemetryDisableMeta } from '../../commands/telemetry/disable/telemetry.disable.js';
import { telemetryEnable, metadata as telemetryEnableMeta } from '../../commands/telemetry/enable/telemetry.enable.js';
import { telemetryStatus, metadata as telemetryStatusMeta } from '../../commands/telemetry/status/telemetry.status.js';
import { valueAdd, metadata as valueAddMeta } from '../../commands/value-propositions/add/value.add.js';
import { valuesList, metadata as valuesListMeta } from '../../commands/value-propositions/list/values.list.js';
import { valueRemove, metadata as valueRemoveMeta } from '../../commands/value-propositions/remove/value.remove.js';
import { valueUpdate, metadata as valueUpdateMeta } from '../../commands/value-propositions/update/value.update.js';
import { workPause, metadata as workPauseMeta } from '../../commands/work/pause/work.pause.js';
import { workRefine, metadata as workRefineMeta } from '../../commands/work/refine/work.refine.js';
import { workResume, metadata as workResumeMeta } from '../../commands/work/resume/work.resume.js';
import { workReview, metadata as workReviewMeta } from '../../commands/work/review/work.review.js';

export const commands: RegisteredCommand[] = [
  {
    path: 'architecture define',
    metadata: architectureDefineMeta,
    handler: architectureDefine
  },
  {
    path: 'architecture update',
    metadata: architectureUpdateMeta,
    handler: architectureUpdate
  },
  {
    path: 'architecture view',
    metadata: architectureViewMeta,
    handler: architectureView
  },
  {
    path: 'audiencePain add',
    metadata: audiencePainAddMeta,
    handler: audiencePainAdd
  },
  {
    path: 'audiencePains list',
    metadata: audiencePainsListMeta,
    handler: audiencePainsList
  },
  {
    path: 'audiencePain update',
    metadata: audiencePainUpdateMeta,
    handler: audiencePainUpdate
  },
  {
    path: 'audience add',
    metadata: audienceAddMeta,
    handler: audienceAdd
  },
  {
    path: 'audiences list',
    metadata: audiencesListMeta,
    handler: audiencesList
  },
  {
    path: 'audience remove',
    metadata: audienceRemoveMeta,
    handler: audienceRemove
  },
  {
    path: 'audience update',
    metadata: audienceUpdateMeta,
    handler: audienceUpdate
  },
  {
    path: 'component add',
    metadata: componentAddMeta,
    handler: componentAdd
  },
  {
    path: 'component deprecate',
    metadata: componentDeprecateMeta,
    handler: componentDeprecate
  },
  {
    path: 'components list',
    metadata: componentsListMeta,
    handler: componentsList
  },
  {
    path: 'component remove',
    metadata: componentRemoveMeta,
    handler: componentRemove
  },
  {
    path: 'component rename',
    metadata: componentRenameMeta,
    handler: componentRename
  },
  {
    path: 'components search',
    metadata: componentsSearchMeta,
    handler: componentsSearch
  },
  {
    path: 'component show',
    metadata: componentShowMeta,
    handler: componentShow
  },
  {
    path: 'component undeprecate',
    metadata: componentUndeprecateMeta,
    handler: componentUndeprecate
  },
  {
    path: 'component update',
    metadata: componentUpdateMeta,
    handler: componentUpdate
  },
  {
    path: 'decision add',
    metadata: decisionAddMeta,
    handler: decisionAdd
  },
  {
    path: 'decisions list',
    metadata: decisionsListMeta,
    handler: decisionsList
  },
  {
    path: 'decision restore',
    metadata: decisionRestoreMeta,
    handler: decisionRestore
  },
  {
    path: 'decision reverse',
    metadata: decisionReverseMeta,
    handler: decisionReverse
  },
  {
    path: 'decision supersede',
    metadata: decisionSupersedeMeta,
    handler: decisionSupersede
  },
  {
    path: 'decision update',
    metadata: decisionUpdateMeta,
    handler: decisionUpdate
  },
  {
    path: 'dependency add',
    metadata: dependencyAddMeta,
    handler: dependencyAdd
  },
  {
    path: 'dependencies list',
    metadata: dependenciesListMeta,
    handler: dependenciesList
  },
  {
    path: 'dependency remove',
    metadata: dependencyRemoveMeta,
    handler: dependencyRemove
  },
  {
    path: 'dependency update',
    metadata: dependencyUpdateMeta,
    handler: dependencyUpdate
  },
  {
    path: 'evolve',
    metadata: evolveMeta,
    handler: evolve
  },
  {
    path: 'goal add',
    metadata: goalAddMeta,
    handler: goalAdd
  },
  {
    path: 'goal approve',
    metadata: goalApproveMeta,
    handler: goalApprove
  },
  {
    path: 'goal block',
    metadata: goalBlockMeta,
    handler: goalBlock
  },
  {
    path: 'goal close',
    metadata: goalCloseMeta,
    handler: goalClose
  },
  {
    path: 'goal codify',
    metadata: goalCodifyMeta,
    handler: goalCodify
  },
  {
    path: 'goal commit',
    metadata: goalCommitMeta,
    handler: goalCommit
  },
  {
    path: 'goals list',
    metadata: goalsListMeta,
    handler: goalsList
  },
  {
    path: 'goal pause',
    metadata: goalPauseMeta,
    handler: goalPause
  },
  {
    path: 'goal qualify',
    metadata: goalQualifyMeta,
    handler: goalQualify
  },
  {
    path: 'goal refine',
    metadata: goalRefineMeta,
    handler: goalRefine
  },
  {
    path: 'goal reject',
    metadata: goalRejectMeta,
    handler: goalReject
  },
  {
    path: 'goal remove',
    metadata: goalRemoveMeta,
    handler: goalRemove
  },
  {
    path: 'goal reset',
    metadata: goalResetMeta,
    handler: goalReset
  },
  {
    path: 'goal resume',
    metadata: goalResumeMeta,
    handler: goalResume
  },
  {
    path: 'goal review',
    metadata: goalReviewMeta,
    handler: goalReview
  },
  {
    path: 'goal show',
    metadata: goalShowMeta,
    handler: goalShow
  },
  {
    path: 'goal start',
    metadata: goalStartMeta,
    handler: goalStart
  },
  {
    path: 'goal submit',
    metadata: goalSubmitMeta,
    handler: goalSubmit
  },
  {
    path: 'goal unblock',
    metadata: goalUnblockMeta,
    handler: goalUnblock
  },
  {
    path: 'goal update',
    metadata: goalUpdateMeta,
    handler: goalUpdate
  },
  {
    path: 'goal update-progress',
    metadata: goalUpdateProgressMeta,
    handler: goalUpdateProgress
  },
  {
    path: 'guideline add',
    metadata: guidelineAddMeta,
    handler: guidelineAdd
  },
  {
    path: 'guidelines list',
    metadata: guidelinesListMeta,
    handler: guidelinesList
  },
  {
    path: 'guideline remove',
    metadata: guidelineRemoveMeta,
    handler: guidelineRemove
  },
  {
    path: 'guideline update',
    metadata: guidelineUpdateMeta,
    handler: guidelineUpdate
  },
  {
    path: 'heal',
    metadata: healMeta,
    handler: heal
  },
  {
    path: 'worker view',
    metadata: workerViewMeta,
    handler: workerView
  },
  {
    path: 'invariant add',
    metadata: invariantAddMeta,
    handler: invariantAdd
  },
  {
    path: 'invariants list',
    metadata: invariantsListMeta,
    handler: invariantsList
  },
  {
    path: 'invariant remove',
    metadata: invariantRemoveMeta,
    handler: invariantRemove
  },
  {
    path: 'invariant update',
    metadata: invariantUpdateMeta,
    handler: invariantUpdate
  },
  {
    path: 'project init',
    metadata: projectInitMeta,
    handler: projectInit
  },
  {
    path: 'project update',
    metadata: projectUpdateMeta,
    handler: projectUpdate
  },
  {
    path: 'relation add',
    metadata: relationAddMeta,
    handler: relationAdd
  },
  {
    path: 'relations list',
    metadata: relationsListMeta,
    handler: relationsList
  },
  {
    path: 'relation remove',
    metadata: relationRemoveMeta,
    handler: relationRemove
  },
  {
    path: 'session compact',
    metadata: sessionCompactMeta,
    handler: sessionCompact
  },
  {
    path: 'session end',
    metadata: sessionEndMeta,
    handler: sessionEnd
  },
  {
    path: 'sessions list',
    metadata: sessionsListMeta,
    handler: sessionsList
  },
  {
    path: 'session start',
    metadata: sessionStartMeta,
    handler: sessionStart
  },
  {
    path: 'telemetry disable',
    metadata: telemetryDisableMeta,
    handler: telemetryDisable
  },
  {
    path: 'telemetry enable',
    metadata: telemetryEnableMeta,
    handler: telemetryEnable
  },
  {
    path: 'telemetry status',
    metadata: telemetryStatusMeta,
    handler: telemetryStatus
  },
  {
    path: 'value add',
    metadata: valueAddMeta,
    handler: valueAdd
  },
  {
    path: 'values list',
    metadata: valuesListMeta,
    handler: valuesList
  },
  {
    path: 'value remove',
    metadata: valueRemoveMeta,
    handler: valueRemove
  },
  {
    path: 'value update',
    metadata: valueUpdateMeta,
    handler: valueUpdate
  },
  {
    path: 'work pause',
    metadata: workPauseMeta,
    handler: workPause
  },
  {
    path: 'work refine',
    metadata: workRefineMeta,
    handler: workRefine
  },
  {
    path: 'work resume',
    metadata: workResumeMeta,
    handler: workResume
  },
  {
    path: 'work review',
    metadata: workReviewMeta,
    handler: workReview
  }
];
